name: CI Pipeline

# Déclencheurs
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Jobs de la pipeline
jobs:
  # Installation des dépendances
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Version de Node.js à utiliser
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

  # Linting
  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run lint
        run: npm run lint

  # Tests unitaires
  unit-test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run unit tests
        run: npm test

  # Tests d'intégration
  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Run integration tests
        run: echo "Hello Integration !"

  # Tests E2E
  e2e-test:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Run E2E tests
        run: echo "Hello E2E !!"

  # Release
  release:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run Release
        run: npx --yes release-it --ci
